---
title: "conditionals_loops.qmd"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

## PART 1

### Conditional Statements

-   **Task 1**

```{r}
pm2_5 <- 126

if (pm2_5 < 100) {
  print("Low to moderate risk")
} else if (pm2_5 >= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else if (pm2_5 >= 150) {
    print("Health risk present")
  }
```

-   **Task 2**

```{r}
species <- "blue whale"

if (str_detect(species, "whale")) {
  print("you found a whale!")
}
```

-   **Task 3**

```{r}
base_burrito <- 6.50

main_ingredient <- "steak"

if (main_ingredient == "veggie") {
  burrito_price = base_burrito
} else if (main_ingredient == "chicken") {
  burrito_price = base_burrito + 3
} else if (main_ingredient == "steak") {
  burrito_price = base_burrito + 3.25
}

print(burrito_price)
```

### For loops

-   **Task 4**

```{r}
fish <- c(goldfish = 8, tetras = 10, guppies = 12 , mollies = 23)

for (i in seq_along(fish)) {
  prop_fish = fish[i]/ sum(fish)
  print(prop_fish)
}

```

-   **Task 5**

```{r}
for (i in seq_along(month.name)) {
  month_n <- i
  month_name <- month.name[i]
  print(paste(month_name, "is month", month_n))
}


```
